config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'

  get 'admin', to: 'events#admin', as: 'admin'
  resources :events do
    resources :attendants, only: %i[new create]
    resources :declarations, only: %i[show new create]
    resources :event_collaborators, only: %i[new create]
    resources :event_attendees, only: %i[new create]
    resources :collab_declarations, only: %i[show new create]
    resources :attendee_declarations, only: %i[show new create]
    get 'attendants', to: 'events#attendants', as: 'asistentes'
    get 'attendees', to: 'events#attendees', as: 'attendees'
    get 'collaborators', to: 'events#collaborators', as: 'colaboradores'
  end

  resources :attendants, only: %i[destroy edit update]
  resources :event_collaborators, only: %i[destroy edit update]
  resources :collaborators, only: %i[new create index destroy edit update]
  resources :attendees, only: %i[new create index destroy edit update]
  resources :event_attendees, only: %i[destroy edit update]

  get 'extra/:id', to: 'attendants#extra', as: 'extra'
  get 'collab_extra/:id', to: 'event_collaborators#extra', as: 'collab_extra'
  get 'attendee_extra/:id', to: 'event_attendees#extra', as: 'attendee_extra'
  get 'success', to: 'success#index'
  get 'full', to: 'success#full', as: 'full'
  get 'ready/:id', to: 'declarations#ready'
  get 'ready2/:id', to: 'attendee_declarations#ready'
  get 'collab_ready/:id', to: 'collab_declarations#collab_ready'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path do %>
    <%= image_tag "logo.png", class: "logo-navbar" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <% if current_user.ficha? %>
            <li class="nav-item">
              <%= link_to "Asistentes por culto",  admin_path, class: "nav-link" %>
            </li>
          <% end %>
          <% if current_user.admin? %>
            <li class="nav-item dropdown">
              <p class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cultos</p>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Crear culto",  new_event_path, class: "dropdown-item" %>
                <%= link_to "Asistentes por culto",  admin_path, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item">
                <%= link_to "Colaboradores",  collaborators_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Asistentes",  attendees_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <p class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <%= current_user.first_name %></p>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Edita tu perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Iniciar Sesión", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>

    </ul>
  </div>
</div>