config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'

  get 'admin', to: 'events#admin', as: 'admin'
  resources :events do
    resources :attendants, only: %i[new create]
    resources :declarations, only: %i[show new create]
    resources :event_collaborators, only: %i[new create]
    resources :event_attendees, only: %i[new create]
    resources :collab_declarations, only: %i[show new create]
    resources :attendee_declarations, only: %i[show new create]
    get 'attendants', to: 'events#attendants', as: 'asistentes'
    get 'attendees', to: 'events#attendees', as: 'attendees'
    get 'collaborators', to: 'events#collaborators', as: 'colaboradores'
  end

  resources :attendants, only: %i[destroy edit update]
  resources :event_collaborators, only: %i[destroy edit update]
  resources :collaborators, only: %i[new create index destroy edit update]
  resources :attendees, only: %i[new create index destroy edit update]
  resources :event_attendees, only: %i[destroy edit update]

  get 'extra/:id', to: 'attendants#extra', as: 'extra'
  get 'collab_extra/:id', to: 'event_collaborators#extra', as: 'collab_extra'
  get 'attendee_extra/:id', to: 'event_attendees#extra', as: 'attendee_extra'
  get 'success', to: 'success#index'
  get 'full', to: 'success#full', as: 'full'
  get 'ready/:id', to: 'declarations#ready'
  get 'ready2/:id', to: 'attendee_declarations#ready'
  get 'collab_ready/:id', to: 'collab_declarations#collab_ready'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  has_one_attached :pase
  has_many :event_attendee, dependent: :destroy
  has_many :attendee_declarations, through: :event_attendee

  def name
    self.first_name + " " + self.last_name
  end

  validates :first_name, :last_name, presence: true
  validates :rut, presence: true, uniqueness: true, format: {with: /\b[0-9|]{7,10}\-[K|k|0-9]/}
  validates :phone, presence: true, format: {with: /[0-9\-\+]{9}/}
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  before_action :set_attendee, only: [:edit, :update, :destroy]

  def index
    @attendees = Attendee.all
  end

  def new
    @attendee = Attendee.new
  end

  def create
    @attendee = Attendee.new(attendee_params)
    @attendee.first_name = @attendee.first_name.capitalize
    @attendee.last_name = @attendee.last_name.titleize
    @attendee.rut = @attendee.rut.upcase

    if @attendee.save
      redirect_to attendees_path
    else
      flash[:alert] = "Algo no funcionó correctamente."
      render :new
    end
  end

  def destroy
    @attendee.destroy
    redirect_to attendees_path
  end

  def edit
  end

  def update
    if @attendee.update(attendee_params)
      flash[:notice] = "El asistente ha sido actualizado con éxito."
      redirect_to attendees_path
    else
      flash[:alert] = "Algo no funcionó correctamente."
      render :edit
    end
  end

  private

  def set_attendee
    @attendee = Attendee.find(params[:id])
    # authorize @event
  end

  def attendee_params
    params.require(:attendee).permit(:first_name, :last_name, :rut, :phone, :email, :pase)
  end
end

app/views/attendees/_form.html.erb
<%= simple_form_for @attendee do |f| %>
  <div class=" form-inputs">
    <%= f.input :first_name, label: "Nombre", error: "Nombre no puede quedar en blanco" %>
    <%= f.input :last_name, label: "Apellidos", error: "Apellidos no puede quedar en blanco"  %>
    <%= f.input :rut, label: "Rut", hint: "Debes escribir el rut sin puntos y con guión. Ej: 12345678-9", error: "Rut inválido o ya está inscrito", placeholder: "Ej: 11111111-1"%>
    <%= f.input :phone, label: "Teléfono", error: "Teléfono inválido", hint: "Debes escribir 9 dígitos"%>
    <%= f.input :email, label: "Correo eléctronico (opcional)"%>
    <%= f.input :pase, as: :file, label: "Sube tu pase de movilidad", error: "Debes adjuntar tu pase de movilidad" %>
  </div>
  <p>* Es necesario que lo completes</p>
  <div class="dropdown-divider"></div>
  <div class="text-center mb-5">
    <%= f.button :submit, "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<div class="container">
  <h3 class="text-center mt-3">Edita al asistente</h2>

  <div class="d-flex flex-column align-items-center mt-2">
    <%= render "form" %>
  </div>
</div>

app/views/attendees/index.html.erb
<div class="container-fluid">
  <h3 class="text-center mt-3">Asistentes</h3>
  <div class="d-flex justify-content-end">
  <p><%= link_to 'Crear nuevo asistente',  new_attendee_path, class: "btn btn-primary my-2" %></p>
  </div>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead class="bg-primary">
        <tr>
          <th scope="col" class="bold text-center" style="color: #fff;">Nombre</th>
          <th scope="col" class="bold text-center" style="color: #fff;">Apellidos</th>
          <th scope="col" class="bold text-center" style="color: #fff;">Rut</th>
          <th scope="col" class="bold text-center" style="color: #fff;">Teléfono</th>
          <th scope="col" class="bold text-center" style="color: #fff;">Correo electrónico</th>
          <th scope="col" class="bold text-center" style="color: #fff;">Pase de movilidad</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @attendees.order(:first_name).each do |attendee| %>
          <tr>
            <td class="text-center"><%= attendee.first_name %></td>
            <td class="text-center"><%= attendee.last_name %></td>
            <td class="text-center"><%= attendee.rut %></td>
            <td class="text-center"><%= attendee.phone %></td>
            <td class="text-center"><%= attendee.email %></td>
            
            
            <td class="text-center">
              <% if attendee.pase.attached? %>
                <%= link_to rails_blob_path(attendee.pase, diposition: "attachment"), target: "_blank" do %>
                  <i class="fas fa-file-pdf"></i>
                <% end %>
              <% end %>
            </td>


            <td class="text-center">
            <%= link_to edit_attendee_path(attendee) do %>
              <i class="fas fa-pen danger"></i>
            <% end %>
            <%= link_to attendee_path(attendee), method: :delete, data: { confirm: "Estás seguro?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
                </td>
          </tr>
        <% end %>
      </tbody>
  </table>
  </div>
</div>

app/views/attendees/new.html.erb
<div class="container">
  <h3 class="text-center mt-3">Regístrate como</h2>
  <h4 class="text-center mb-3 bold">Asistente Regular</h4>

  <div class="d-flex flex-column align-items-center mt-2">
    <%= render "form" %>
  </div>
</div>