config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'

  get 'admin', to: 'events#admin', as: 'admin'
  resources :events do
    resources :attendants, only: %i[new create]
    resources :declarations, only: %i[show new create]
    resources :event_collaborators, only: %i[new create]
    resources :event_attendees, only: %i[new create]
    resources :collab_declarations, only: %i[show new create]
    resources :attendee_declarations, only: %i[show new create]
    get 'attendants', to: 'events#attendants', as: 'asistentes'
    get 'attendees', to: 'events#attendees', as: 'attendees'
    get 'collaborators', to: 'events#collaborators', as: 'colaboradores'
  end

  resources :attendants, only: %i[destroy edit update]
  resources :event_collaborators, only: %i[destroy edit update]
  resources :collaborators, only: %i[new create index destroy edit update]
  resources :attendees, only: %i[new create index destroy edit update]
  resources :event_attendees, only: %i[destroy edit update]

  get 'extra/:id', to: 'attendants#extra', as: 'extra'
  get 'collab_extra/:id', to: 'event_collaborators#extra', as: 'collab_extra'
  get 'attendee_extra/:id', to: 'event_attendees#extra', as: 'attendee_extra'
  get 'success', to: 'success#index'
  get 'full', to: 'success#full', as: 'full'
  get 'ready/:id', to: 'declarations#ready'
  get 'ready2/:id', to: 'attendee_declarations#ready'
  get 'collab_ready/:id', to: 'collab_declarations#collab_ready'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendants, dependent: :destroy
  has_many :declarations, dependent: :destroy
  has_many :event_collaborators, dependent: :destroy
  has_many :event_attendees, dependent: :destroy
  has_many :collaborators, through: :event_collaborators
  has_many :attendees, through: :event_attendees

  validates :name, :date, :quantity, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_event2, only: [:attendants, :collaborators]

  def index
    @events = Event.all
  end

  def show
    @event_collaborator = EventCollaborator.new
    @attendants = @event.attendants
    @collaborators = @event.event_collaborators
    @attendees = @event.event_attendees
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Culto #{@event.name}",
        page_size: 'Letter',
        template: "events/show.html.erb",
        layout: "pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.seats = Array.new
    @event.collabs = 13
    @event.quantity = 32
    @event.collab_seat = Array.new

    if @event.save
      redirect_to root_path
    else
      flash[:alert] = "Algo no funcionó correctamente."
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to root_path
      flash[:notice] = "El evento ha sido actualizado con éxito."
    else
      flash[:alert] = "Algo no funcionó correctamente."
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end

  def admin
    @events = Event.all
  end

  def attendants
    @attendants = @event.attendants
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Culto #{@event.name}",
        page_size: 'Letter',
        template: "events/attendants.html.erb",
        layout: "pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end

  def collaborators
    @collaborators = @event.event_collaborators
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Culto #{@event.name}",
        page_size: 'Letter',
        template: "events/collaborators.html.erb",
        layout: "pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end
  private

  def set_event
    @event = Event.find(params[:id])
    # authorize @event
  end

  def set_event2
    @event = Event.find(params[:event_id])
  end

  def event_params
    params.require(:event).permit(:name, :date, :quantity, :seats)
  end
end

app/views/events/_attendants.html.erb
<div class="divTableBody">
  <% @attendants.order(first_name: :asc).each do |attendant| %>
    <%= content_tag :div, class: 'divTableRow', id: dom_id(attendant) do %>
      <div class="divTableCell"><%= attendant.first_name %></div>
      <div class="divTableCell"><%= attendant.last_name %></div>
      <div class="divTableCell"><%= attendant.rut %></div>
      <div class="divTableCell"><%= attendant.phone %></div>
      <div class="divTableCell"><%= attendant.email %></div>
      <div class="divTableCell"><%= attendant.seat %></div>
      <div class="divTableCell">
        <%= link_to rails_blob_path(attendant.pase, diposition: "attachment"), target: "_blank" do %>
          <i class="fas fa-file-pdf"></i>
        <% end %>
      </div>
      <div class="divTableCell">
        <%= link_to extra_path(attendant), remote: true do %>
          <i class="fas fa-thermometer-three-quarters"></i>
          <%= attendant.temperature %>
        <% end %>
      </div>

      <% if attendant.declaration.present? %>
        <div class="divTableCell">
          <%= link_to 'Ver declaración', event_declaration_path(attendant.event, attendant.declaration), class: "btn btn-success see-declaration", target: "_blank" %>
        </div>
      <% else %>
        <div class="divTableCell">
          <%= link_to "Solicitar declaración", "https://wa.me/56#{attendant.phone}?text=Hola%20#{attendant.first_name},%20haz%20click%20en%20el%20siguiente%20link%20para%20que%20completes%20tu%20Declaración%20Jurada:%20https://iap-nacto.herokuapp.com/events/#{attendant.event.id}/declarations/new", class: "btn btn-danger see-declaration", target: "_blank"%>
        </div>
      <% end %>

      <div class="divTableCell">
        <%= link_to edit_attendant_path(attendant), remote: true do %>
          <i class="fas fa-pen danger"></i>
        <% end %>
        <%= link_to attendant_path(attendant), method: :delete, data: { confirm: "Estás seguro?" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">

          </div>
        </div>
      </div>


    <% end %>
  <% end %>
</div>

app/views/events/_event_attendees.html.erb
<div class="divTableBody">
  <% @attendees.each do |event_attendee| %>
    <%= content_tag :div, class: 'divTableRow', id: dom_id(event_attendee) do %>
      <div class="divTableCell"><%= event_attendee.attendee.first_name %></div>
      <div class="divTableCell"><%= event_attendee.attendee.last_name %></div>
      <div class="divTableCell"><%= event_attendee.seat %></div>
      <div class="divTableCell">
        <% if event_attendee.attendee.pase.attached? %>
          <%= link_to rails_blob_path(event_attendee.attendee.pase, diposition: "attachment"), target: "_blank" do %>
            <i class="fas fa-file-pdf"></i>
          <% end %> 
        <% end %>
      </div>

      <div class="divTableCell">
        <%= link_to attendee_extra_path(event_attendee), remote: true do %>
          <i class="fas fa-thermometer-three-quarters"></i>
          <%= event_attendee.temperature %>
        <% end %>
      </div>

      <% if event_attendee.attendee_declaration.present? %>
        <div class="divTableCell">
          <%= link_to 'Ver declaración', event_attendee_declaration_path(event_attendee.event, event_attendee.attendee_declaration), class: "btn btn-success see-declaration", target: "_blank" %>
        </div>
      <% else %>
        <div class="divTableCell">
          <%= link_to "Solicitar declaración", "https://wa.me/56#{event_attendee.attendee.phone}?text=Hola%20#{event_attendee.attendee.first_name},%20haz%20click%20en%20el%20siguiente%20link%20para%20que%20completes%20tu%20Declaración%20Jurada:%20https://iap-nacto.herokuapp.com/events/#{@event.id}/attendee_declarations/new", class: "btn btn-danger see-declaration", target: "_blank"%>
        </div>
      <% end %>


      <div class="divTableCell">
        <%= link_to edit_event_attendee_path(event_attendee), remote: true do %>
          <i class="fas fa-pen danger"></i>
        <% end %>
        <%= link_to event_attendee_path(event_attendee), method: :delete, data: { confirm: "Estás seguro?" }, remote: true do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>


      <div class="modal fade" id="attendeeModal" tabindex="0" aria-labelledby="attendeeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">

          </div>
        </div>
      </div>


    <% end %>
  <% end %>
</div>

app/views/events/_event_collaborators.html.erb
<div class="divTableBody">
  <% @collaborators.each do |event_collaborator| %>
    <%= content_tag :div, class: 'divTableRow', id: dom_id(event_collaborator) do %>
      <div class="divTableCell"><%= event_collaborator.collaborator.first_name %></div>
      <div class="divTableCell"><%= event_collaborator.collaborator.last_name %></div>
      <div class="divTableCell">
        <%= link_to "Avisar participación como colaborador", "https://wa.me/56#{event_collaborator.collaborator.phone}?text=Hola%20#{event_collaborator.collaborator.first_name},%20no%20te%20olvides%20que%20esta%20semana%20tienes%20participación%20como%20colaborador%20en%20el%20culto.%20Nos%20vemos!", class: "btn btn-info see-declaration", target: "_blank"%>
      </div>
      <div class="divTableCell"><%= event_collaborator.seat %></div>
      <div class="divTableCell">
        <%= link_to rails_blob_path(event_collaborator.collaborator.pase, diposition: "attachment"), target: "_blank" do %>
          <i class="fas fa-file-pdf"></i>
        <% end %>
      </div>

      <div class="divTableCell">
        <%= link_to collab_extra_path(event_collaborator), remote: true do %>
          <i class="fas fa-thermometer-three-quarters"></i>
          <%= event_collaborator.temperature %>
        <% end %>
      </div>

      <% if event_collaborator.collab_declaration.present? %>
        <div class="divTableCell">
          <%= link_to 'Ver declaración', event_collab_declaration_path(event_collaborator.event, event_collaborator.collab_declaration), class: "btn btn-success see-declaration", target: "_blank" %>
        </div>
      <% else %>
        <div class="divTableCell">
          <%= link_to "Solicitar declaración", "https://wa.me/56#{event_collaborator.collaborator.phone}?text=Hola%20#{event_collaborator.collaborator.first_name},%20haz%20click%20en%20el%20siguiente%20link%20para%20que%20completes%20tu%20Declaración%20Jurada:%20https://iap-nacto.herokuapp.com/events/#{@event.id}/collab_declarations/new", class: "btn btn-danger see-declaration", target: "_blank"%>
        </div>
      <% end %>


      <div class="divTableCell">
        <%= link_to edit_event_collaborator_path(event_collaborator), remote: true do %>
          <i class="fas fa-pen danger"></i>
        <% end %>
        <%= link_to event_collaborator_path(event_collaborator), method: :delete, data: { confirm: "Estás seguro?" }, remote: true do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>


      <div class="modal fade" id="collabModal" tabindex="-1" aria-labelledby="collabModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">

          </div>
        </div>
      </div>


    <% end %>
  <% end %>
</div>

app/views/events/_table_header.html.erb
<div class="divTableHeading">
  <div class="divTableRow">
    <div class="divTableHead">Nombre</div>
    <div class="divTableHead">Apellidos</div>
    <div class="divTableHead">Rut</div>
    <div class="divTableHead">Teléfono</div>
    <div class="divTableHead">Email</div>
    <div class="divTableHead">Asiento</div>
    <div class="divTableHead">PDM</div>
    <div class="divTableHead">Tº</div>
    <div class="divTableHead">Declaración</div>
    <div class="divTableHead"></div>
  </div>
</div>

app/views/events/_table_header2.html.erb
<div class="divTableHeading">
  <div class="divTableRow">
    <div class="divTableHead">Nombre</div>
    <div class="divTableHead">Apellidos</div>
    <div class="divTableHead"></div>
    <div class="divTableHead">Asiento</div>
    <div class="divTableHead">PDM</div>
    <div class="divTableHead">Tº</div>
    <div class="divTableHead">Declaración</div>
    <div class="divTableHead"></div>
  </div>
</div>

app/views/events/_table_header3.html.erb
<div class="divTableHeading">
  <div class="divTableRow">
    <div class="divTableHead">Nombre</div>
    <div class="divTableHead">Apellidos</div>
    <div class="divTableHead">Asiento</div>
    <div class="divTableHead">PDM</div>
    <div class="divTableHead">Tº</div>
    <div class="divTableHead">Declaración</div>
    <div class="divTableHead"></div>
  </div>
</div>

app/views/events/admin.html.erb
<div class="container">
  <h3 class="text-center mt-3">Asistentes por culto</h3>
  <div class="d-flex flex-column align-items-center">
    <% @events.order(date: :desc).each do |event| %>
          <%= link_to event_path(event) do %>
            <div class="d-flex flex-column align-items-center btn btn-primary my-3">
              <p><%= event.name %></p>
              <p><%= event.quantity %> cupos disponibles</p>
              <p><%= event.collabs %> colaboradores disponibles</p>
            </div>
          <% end %>
    <% end %>
  </div>
</div>

app/views/events/attendants.html.erb
<div class="container-fluid">
  <h3 class="text-center mt-3"><%= @event.name %></h3>
  <p class="text-center my-2"><%=pluralize @attendants.count, "asistente" %></p>
  <div class="table-responsive">
    <div class="divTable paleBlueRows">
      <div class="divTableHeading">
        <div class="divTableRow">
          <div class="divTableHead">Nombre</div>
          <div class="divTableHead">Apellidos</div>
          <div class="divTableHead">Rut</div>
          <div class="divTableHead">Teléfono</div>
          <div class="divTableHead">Email</div>
          <div class="divTableHead">Asiento</div>
          <div class="divTableHead">Tº</div>
          <div class="divTableHead">Declaración</div>
        </div>
      </div>
      <div class="divTableBody">
        <% @attendants.order(seat: :asc).each do |attendant| %>
          <%= content_tag :div, class: 'divTableRow', id: dom_id(attendant) do %>
            <div class="divTableCell"><%= attendant.first_name %></div>
            <div class="divTableCell"><%= attendant.last_name %></div>
            <div class="divTableCell"><%= attendant.rut %></div>
            <div class="divTableCell"><%= attendant.phone %></div>
            <div class="divTableCell"><%= attendant.email %></div>
            <div class="divTableCell"><%= attendant.seat %></div>
            <div class="divTableCell"><%= attendant.temperature %></div>
            <% if attendant.declaration.present? %>
              <div class="divTableCell">
                <%= "SI" %>
              </div>
            <% else %>
              <div class="divTableCell">
                <%= "NO" %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/collaborators.html.erb
<div class="container-fluid">
  <h3 class="text-center mt-3"><%= @event.name %></h3>
  <p class="text-center my-2"><%=pluralize @collaborators.count, "colaboradore" %></p>
  <div class="table-responsive">
    <div class="divTable paleGreenRows">
      <div class="divTableHeading">
        <div class="divTableRow">
          <div class="divTableHead">Nombre</div>
          <div class="divTableHead">Apellidos</div>
          <div class="divTableHead">Rut</div>
          <div class="divTableHead">Teléfono</div>
          <div class="divTableHead">Email</div>
          <div class="divTableHead">Asiento</div>
          <div class="divTableHead">Tº</div>
          <div class="divTableHead">Declaración</div>
        </div>
      </div>

      <div class="divTableBody">
        <% @collaborators.each do |event_collaborator| %>
          <%= content_tag :div, class: 'divTableRow', id: dom_id(event_collaborator) do %>
            <div class="divTableCell"><%= event_collaborator.collaborator.first_name %></div>
            <div class="divTableCell"><%= event_collaborator.collaborator.last_name %></div>
            <div class="divTableCell"><%= event_collaborator.collaborator.rut %></div>
            <div class="divTableCell"><%= event_collaborator.collaborator.phone %></div>
            <div class="divTableCell"><%= event_collaborator.collaborator.email %></div>
            <div class="divTableCell"><%= event_collaborator.seat %></div>
            <div class="divTableCell"><%= event_collaborator.temperature %></div>

            <% if event_collaborator.collab_declaration.present? %>
              <div class="divTableCell">
                <%= "SI" %>
              </div>
            <% else %>
              <div class="divTableCell">
                <%= "NO" %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <h3 class="text-center mt-3">Selecciona el culto que deseas asistir</h2>
  <p class="text-center">Las inscripciones están permitidas solo para aquellos que tengan su esquema de vacunación completo y su pase de movilidad habilitado</p>
  <div class="d-flex flex-column align-items-center">
    <% if @events.size > 0 %>
      <% @events.order(date: :asc).each do |event| %>
        <% if event.quantity > 0 %>
          <% if event.date >= Date.today %>
            <%= link_to new_event_event_attendee_path(event) do %>
              <div class="d-flex flex-column align-items-center justify-content-center my-3 btn btn-primary">
                <p><%= event.name %></p>
                <p><%= event.quantity %> cupos disponibles</p>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
    <p class="text-center">No hay cultos disponibles</p>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <h2 class="text-center mt-2">Nuevo culto</h2>

  <div class="container d-flex flex-column align-items-center">
    <%= simple_form_for @event do |f| %>
      <div class=" form-inputs">
        <%= f.input :name, label: "Nombre del culto", error: "Nombre del culto no puede quedar en blanco" %>
        <%= f.input :date, as: :date, order: [:day, :month, :year], label: "Fecha" %>
      </div>
      <div class="dropdown-divider"></div>
      <div class="text-center">
        <%= f.button :submit, "Guardar", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container-fluid">
  <h3 class="text-center mt-3"><%= @event.name %></h3>
  <p class="text-center my-2"><%=pluralize @attendants.count, "asistente" %></p>
  <div class="d-flex justify-content-end">
    <%= link_to 'Descargar PDF', event_asistentes_path(::Event.find(params[:id]), format: :pdf), class: "btn btn-primary mb-2", target: "_blank" %>
  </div>


  <div class="table-responsive">
    <div class="divTable paleBlueRows">
      <%= render "table_header" %>
      <%= render "attendants" %>
    </div>
  </div>

    <div class="table-responsive mt-5">
    <div class="divTable paleBlueRows">
      <%= render "table_header3" %>
      <%= render "event_attendees" %>
    </div>
  </div>

  <h4 class="text-center my-2 mt-5">Colaboradores</h4>
  <p class="text-center"><%=pluralize @collaborators.count, "inscrito" %></p>
  <div class="d-flex justify-content-end">
    <%= link_to 'Descargar PDF', event_colaboradores_path(::Event.find(params[:id]), format: :pdf), class: "btn btn-info mb-2", target: "_blank" %>
  </div>

  <div class="table-responsive">
    <div class="divTable paleGreenRows mb-3">
      <%= render "table_header2" %>
      <%= render "event_collaborators" %>
    </div>
  </div>

  <div class="d-flex justify-content-center" id="somediv">
    <%= render "event_collaborators/form" %>
  </div>
</div>